#!/bin/bash

echo "Sisesta enda vanus: "
read vanus

if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "olen nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "oled taiskasvanu"
elif test $vanus -ge 63
then
	echo "oled seenior"
else
	echo "vigane sisend"
fi
