#!/bin/bash

echo "Sisesta kuu number: "
read number

if test $number -eq 1 -o $number -eq 2 -o $number -eq 12
then
	echo "Hetkel on talv"
elif test $number -ge 3 -a $number -le 5
then
	echo "Hetkel on kevad"
elif test $number -ge 6 -a $number -le 8
then
	echo "Hetkel on suvi"
elif test $number -ge 9 -a $number -le 11
then
	echo "Hetkel on sugis"
else
	echo "vigane sisend"
fi
